version: '3'

networks:
    mynetwork:
        name: mynetwork
        external: true

services:
    mongo_pagamento:
        image: mongo
        command: mongod --port 27019
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27019:27019
        networks:
            - mynetwork
        container_name: mongo_pagamento

    node_pagamento:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: node_pagamento
        ports:
            - '5001:5001'
        depends_on:
            - mongo_pagamento
        networks:
            - mynetwork
